app = "art-o-mart-backend"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "5000"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    method = "GET"
    path = "/api/health"
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"

[deploy]
  release_command = "echo 'Deployment starting...'"

[[services]]
  protocol = "tcp"
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    method = "GET"
    path = "/api/health"
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"

[machine]
  memory = "1gb"
  cpus = 1

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"