app = "art-o-mart-backend"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "5000"
  AI_MODEL = "gemini-2.0-flash-001"
  AI_TEMPERATURE = "0.7"
  AI_MAX_TOKENS = "2000"
  JWT_EXPIRY = "7d"
  LOG_LEVEL = "info"
  RATE_LIMIT_MAX = "1000"
  RATE_LIMIT_MAX_REQUESTS = "1000"
  RATE_LIMIT_WINDOW_MS = "900000"
  ENABLE_WEBSOCKETS = "true"
  ENABLE_AI_FEATURES = "true"
  ENABLE_RATE_LIMITING = "true"
  ENABLE_REQUEST_LOGGING = "true"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/api/health"
    interval = "30s"
    timeout = "15s"
    grace_period = "60s"

[deploy]
  release_command = "echo 'Art-O-Mart backend deployment starting...'"

[machine]
  memory = "2gb"
  cpus = 2

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"